name: CI

on:
  push:
    branches: [main, release/*]

jobs:
  test:
    uses: ./github/workflows/test.yml

  storybook:
    name: storybook (ubuntu-20.04)
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Required for Chromatic
          lfs: true

      - uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Restore cache
        uses: actions/cache@v2
        with:
          path: |
            .yarn/cache
            **/node_modules
          key: v5-${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: v5-${{ runner.os }}-yarn-

      - run: yarn install --immutable

      - run: yarn workspace @foxglove/studio-base run storybook:build

      # Chromatic only runs on pushes or pulls to our source repo
      - uses: chromaui/action@v1
        if: ${{ github.event.repository.full_name == 'foxglove/studio' }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: f50040a29fb8
          storybookBuildDir: packages/studio-base/storybook-static
          autoAcceptChanges: main
          exitOnceUploaded: true

  integration:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]

    name: integration (${{ matrix.os }})

    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true

      - uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Restore cache
        uses: actions/cache@v2
        with:
          path: |
            .yarn/cache
            **/node_modules
          key: v5-${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: v5-${{ runner.os }}-yarn-

      - run: yarn install --immutable

      - name: test:integration
        if: matrix.os == 'ubuntu-20.04'
        uses: GabrielBB/xvfb-action@v1.5
        with:
          working-directory: ./
          run: yarn run test:integration

      - name: test:integration
        if: matrix.os != 'ubuntu-20.04'
        run: yarn run test:integration
