name: CI

on:
  pull_request:

# https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#concurrency
# New commits cancel previous runs
concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  test:
    uses: ./github/workflows/test.yml
